kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: httpd-frontend
spec:
  scaleTargetRef:
    kind: Deployment
    name: httpd-frontend
    apiVersion: apps/v1
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
