apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
  - hpa.yaml
  - route.yaml
# Resource include sealed secret yaml file
  - sealed-mysecret.yaml
  - sealed-mysecret2.yaml

patchesStrategicMerge:
- deployment.yaml

configMapGenerator:
  - name: myconfig
    envs:
      - env.config
# Add sealed secret file to configmap and at deployment reference both secret name and configmap
  - name: mysecretconfig
    files:
      - sealed-mysecret.yaml
      - sealed-mysecret2.yaml
