apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
  - hpa.yaml
  - route.yaml
  - sealed-mysecret.yaml

patchesStrategicMerge:
- deployment.yaml

configMapGenerator:
  - name: myconfig
    envs:
      # configfile is used as key
      - env.config

configurations:
  - configuration/sealed-secret-config.yaml

#generatorOptions:
#  annotations:
#    sealedsecrets.bitnami.com/managed: "true"
#    sealedsecrets.bitnami.com/namespace-wide: "true"

secretGenerator:
  - name: mysecret