apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
  - hpa.yaml
  - route.yaml
  - sealed-mysecret.yaml

patchesStrategicMerge:
- deployment.yaml

configMapGenerator:
  - name: myconfig
    envs:
      # configfile is used as key
      - env.config
  - name: mysecretconfig
    files:
      - sealed-mysecret.yaml





# generate empty secrets to provide hashed names for pod specs
#secretGenerator:
#  - name: mysecret
#    type: Opaque
#  - name: db-password
#    literals:
#      - password=1234


#generatorOptions:
#  annotations:
#    sealedsecrets.bitnami.com/managed: "true"
#    sealedsecrets.bitnami.com/namespace-wide: "true"
#  labels:
#    currently-used-by-kustomize: "true"

#configurations:
#  - configuration/sealed-secret-config.yaml