apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: demo
spec:
  encryptedData:
    password: AgA0cWwc4E+s0lwRrkbXFQwE4cE2dZrKTBJGmo3QrtLN/9WlxI356K5kjahenTI9OD3qBNbg2llm4TWThbnYKyflIktp6Lbm77/cqYu0K6AUB4S4QRTFYUzjwytAYlalviMyvPQPBN8TOIZMw5uVbTKGZ3G8vqpxgqcE9ATfIqtkgz9zqssbk6NY8NJDno/GaA5nmTBFf+3ZnPVniMJizIvfr/tMpeAEIQYRcvBF01dFkDTbCtHC/yoX0PuGJZHjlkWlNHyUZUQiu69qjZV7+YNWK6YVGjcHQbcnEfTMKqLnJvPMBo/l14CJL9iDp+FNOg8NHqxYeLUaDp0Q+8T9HUlNaUU/8D1jH+R0YxxRxXw+Y2g2u456lwA6bw2YVBvoF9ZqIYy9i3EdUJBb035yEtKq4UXu8O7Mg1pw56YMuLUgF/eTMus6NtSBk/8n1PNEqf2C/Fbxcq0LhA/hyVJbqg7+hXq1fFjW1RkJfWPq/J9lw5bt/BxqFEnKBnFk15rI0NGGUseHkMHPDRm3Isz2CdUqx/7S7+1kCbK14cNtClmFa6+YSzfaW59NLdakIwQfALBr5CujuMqx5RN17y5CCcf+u6bYg+sphr5UaS+uOlwOaglJBluX92RysXtaZSTcuYuENshuGJUgzjwIAtriEEAsy3ahhs4JO4sSmMm1F4UUliB3CB/s7A+p7LU7e2gp/qbTFz64Awy/GAmk+48=
    username: AgBh7lmn+xgJguMOTfRnwlo0KBSs7CZXUZGX2naYTy2nxTOLWKQ5PA46wz5qvB51ZyzFXlOsYXO7EJlFyRwOB6uCcj88yzgnKF2J5p8PbbFfT919pDk3T2NRKu1rAUt0dQm119tPMqP5m0tnUCc3hQuqmWBM1tBZvPNkBP93BW/cgOfesGANJZ7EZVBugVGfFLveFbC4hrGGQtzNnHUPbFfJpXTl5wn2zmjjvFGI0rnZ5BKsoZ8PQFzCzXk0sWy3o/yTTbcb8C5bCGSGyq/M0lnv93ATkIVFQzaIWy6xuvB48o63aAAMSp3/O40GUojM32iEyerficncmhAIctZju8vSoUoLxr9hvkaivgu/ifm58M8W+trFWRIHIqd7Tog5TLkwArjHiN0jL6OT1SMVhiCcSxYSRKFFLQGscvSCGchls0A8lF0BiM4ulZnUF/cCuHtGjYWbiRXDsW9kJ6TYgjzhSeguI0hEcI6+uW/rliMyCKpeRYW5msviYglVQ0dtUhrTf0daOo85hURRANgMq/9i2knes6lE/0GcRGNxAFhSIoEgMW1FO/tUiUOW2r+jpWxgXh5T2WUwu30qoRH/HComT20F1Vy8PJntlWfYk0jVgVQuWYJa2UAwCKWsvEBnErqYen+c4tNJ2KYUejnRJKfBg5ctJxMgROCy2rQ28P26tdBXaHSZ+RPcNIG0EgbL2yF6izXXzHqT
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: demo
    type: Opaque