apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: demo
spec:
  encryptedData:
    password: AgB8PEUZH9C3BqcRfN0foxfYPogYhWzRKs5HogV/DA4zl4EZMOcBXv8TiogtvaDKEgZq8OdwLuJQ4Zlnu/v5EEL7lxwEsLpG/qs8u519VOhU3t1XuKohuMlvgWXrn3yxgn6MTSMO71hiB5CG2PW/xCe4HgVD6YkOu0CExbNboYPJJhvj7PkqXAmEFK7SvaNv8eGaxhacm0RGAZDQji7G7JcVJYrVS/8BNqLO1fWPcru1ShALljXSZCAzpkpIHP4/0Eh9ph0RSuNEpnCNfGS2hlVaTLMQJaSLQCe89ASTe4e/XJUCjGqix2DMKnClC6PYylAM8P2ZukS/brZ34JDEkNI13SmMnerPECDU38xkADJe8CeeTi+ubINmvggbJBs0dRgJTh3ud0dO4fM/8rpPnxeVCCopUGz09Xx7B78zTTIyzMcNqO1rXYFy+kU95cxDnOx7GSXD9aO8QbO6EIlSih6xqfjcyV15SqEUjWcSBgOSSHfZGbJPJy9KZQ12Ab9W48HevZcxDhP30bjWDduUNqpmB3hLCM+CM5ynKgMwK12QXLfskOqC7vfoLJguausc+rZ3jEZSyYsYxk3bP625EtpjhPLylIF7NTLf//TuBHdLWofFg3i6tSqh3SsotRVCq0O3UmVDZt08RP5D0lbrDrlVmG0WeaKSEdRzYJgZol+XJ7JOsoVzHm7wngJAxTdOWQZ1MHwLOGtKjQ==
    username: AgAM/7qnEn2HMIX3LtlrKAMgmzJOfxZnCPlYXFb1iOkv1k75bu4PHn5T/HH4C5oz2p7YlIumvsf0AS/n1aFFWoBc1p5JtCGXgUe0yfNRLSbQMc8RrhigX123JGNDkgUn2Tp8PrPb74cEbrYkXZPitl3vEOuGbLPUtFwMLx5nJVSz3TAamMn/pd3148KHi+RTpLm868x5/4c8xGFR00JvPMY2MuZWTJAJTARNHwEe25G1nY7MBZVqYZOSyrcv34mhFLl00Bo0oaviiLEo4b+sUz+v4hQzoSPLw7Kp6DFA5uKn7XEXPWAxh1HSNx1kL/ZUi4l01tt36sU8OMY1iQPp50mMN1O+3FEquWNlrO1uLzX9EYZhIP0nFZvT4gW1lwRz7GdR715eunQsoGYEFu4YKq5+/VpU4aY7Sd88svf1HBdwyjCOhiKsZ4S1dbWfQCtLyJzZ5jVZNIxvQtiCeFWub2kQYHf9QOI74O0v0P2x79owTZUET9lSk2HVTcFnaLCbZ0aWdgQq69azSsv381IkNZIEaC8hjuKJP0iQXnksaqOvxa4yaDkiqFQpr16Y3Iu7lNd5SU0A2+ETVc+hALhVYX9lSaClLcxCGVotRGESYMeXbwf+d+vku3rlp0Vl02GnLoxb/fTSHpYvC1j0XG6d3eAW3mkKRjEs9RQyS8w1bkIs0l74T2APMbJrm6tVKshTIFCoIZiVpx2m
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: demo
    type: Opaque