apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: demo
spec:
  encryptedData:
    password: AgBgPWOO/x23J3mMC6y4lnuU/VKFwKo0woNFcmDaYqL5Dc3vb93j5egS3rPb4ucKSg9OD4fX8Pj8y8XC25DdilSTJmum4MKRr/bNtX97rkXB83ruC/VWVcoLnwiMU9E4QMHblmtqzReZi9ZUh3KbcHryrxKCavYrxZ8zQtS3opDk7QE2itOWN6g64qPkaDjEhaxfSno4vG9xFUlYYRcXhtza3W8DlxaanHDDQBBHFHP9CIsF5PH5Yhssll0m73GqfNQHYu5A6eJxoERtzfoCG2vIaemKysKUtFP+N3yvLVK+WamRLduSBgYJi9dUKfyiTebOVFqgVYULgrdsNi/sicSAiOd6ZRLZnKZif71c6v9HVb+VB2Ll4zNd7RUwtbWMkNAuG3udq7YMF1cJ1VZozT5BSj3a7tfiFZ2b6okq+UxkZupTKnZTC7bxvx4efmqLPku5hVy3zY7lqzXVhLJVXuUrIPn4VuKLC+p40L9OmzCY/Nzy6ecPyeC3tHimd9dFcNnyJsW3vy3IXYDMq8br3IdAROs1FwQ7UpDPHNWNfXHkVtVVTFDcWRGroOC0GT/DvcPi33fQL3g6BKpVivREYaUEYS9cKgu3tgy5o3vUquFdEMemwndBvZO6r0zVdAhxcWRUcaPhFRiv9KP7eiVFZFt8JJ1TUt6xynqbfnbNAMWHmJ9FiMQrblyUfYY80t4XYNm0s52vXy0/6w==
    username: AgAiwETtf1lNbex4C8wXsDXTdlYSB0iC47nSXf/SKawv6q01YmhlCMhfyADqhh97/DtGgZ8MksN1Pv7619aPpGj/mg5Mu6cCo6+0X6IVCxe4211ls4GoUqMye3G+HEs0j9Mcdpf+hOyn9EqvxfvOoZErWmtPPEO6lUUhd3QmtJvDZk8v6YAlMNPhhF++T5gBVAPPSgGjbOJxCJNLC47833vBXDw54Oit7Wx8cF7lvhR1duOFPxVLp50gW5CuvWfqHgooiyxv7pLuClRb5VwJx4IrMrRmsGVZGu7jqJnBSKng64w+nRTdop/5fWcNzEWSVaqK+HpBHYNGqkL9hX23sZ3TzcNIj2RNv2bpNgQklWAZ+dXMdndnVEaEdANC1wAAm3E7erVd72nVzOuauM6SZoIQWghVKb73Bg4DeNtMBidpGrVE5auO6HSWL3XE1sxbG8K+oJxfX1oVjdSNzmOzoEyXReOn1Ns9s4+SL5kg04K4goyzY7+S2og3XdraoZ8qUyzrMSK9bYtLIlVb6z3ele/BSZANbb+khmMd90OpD0wvSGbDqDdZZdZzzZeN1ViJTHlliFv7lL0+itIm5cNB67shYUmzVnh1S3mxmHC1xhMnD6s7hTmHEYLDs6nqum+vK8UaNCse9pYLc47MWqv2c0dHb2As80yIZD01pI6JzsJsAoslF8c/QNg9Z3/ANfx7Bgq7XWCf7MLZ
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: demo
    type: Opaque